### ISSUE TITLE
Standalone installation fails with node v12.0.0 and above

### ISSUE THREAD

**Issue by DrTexx** [jackw01/liora#3]
## Issue
One of the required node packages, `lame`, fails to build with node v12 and above.
- https://github.com/TooTallNate/node-lame/issues/92
- https://github.com/TooTallNate/node-lame/issues/101

This cuts the installation of package short if using said versions.

Other than using node v11 or below, the other suggested workaround in the thread linked is to use a forked version of the codebase, where the issue has been resolved. A PR was created too, however this may take some time as the project appears to be maintained infrequently.

Perhaps for the moment the readme should state v8 through v11 will work, with a note on node-lame being the cause.

## Side note
Installation also failed for me with node v8.0.0 as Python is not installed and available ootb with the instance I'm using. I haven't done much further testing on this as I'm just going to try node v11.

### Update 1
Never mind, this also happened with v11.15.0
```
> ref@1.3.5 install /home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/liora/node_modules/ref
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/home/liora/.nvm/versions/node/v11.15.0/bin/node" "/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/liora/node_modules/ref
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
### Update 2
After installing python, I'm now receiving this error (using node v11.15.0)
```
Failed to execute '/home/liora/.nvm/versions/node/v11.15.0/bin/node /home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/liora/node_modules/snowboy/lib/node/binding/Release/node-v67-linux-x64/snowboy.node --module_name=snowboy --module_path=/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/liora/node_modules/snowboy/lib/node/binding/Release/node-v67-linux-x64' (1)
  COPY Release/snowboy.nodeinstall: info lifecycle liora@1.2.0~postinstall: liora@1.2.0
cp: cannot stat 'Release/obj.target/snowboy.node': No such file or directoryliora@1.2.0
snowboy.target.mk:151: recipe for target 'Release/snowboy.node' failed
make: *** [Release/snowboy.node] Error 1
make: Leaving directory '/home/liora/.nvm/versions/node/v11.15.0/lib/node_modules/liora/node_modules/snowboy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```
### Update 3
Installation appears to work okay in node v11.15.0 when the --no-optional flag is used

**Comment by jackw01** [comment]
Seems to be just the packages for the voice command feature, that was experimental anyways and I made them optional because I had issues installing them myself.
